//! Adds some helpful utilities for working with bits and bytes.
#![cfg_attr(feature = "docs", doc = "Check out the [changelog][changelog].")]
#![cfg_attr(feature = "docs", doc = "## Feature flags")]
#![cfg_attr(feature = "docs", doc = document_features::document_features!())]
//! ## License
//!
//! This project is licensed under the MIT or Apache-2.0 license.
//! You can choose between one of them if you use this work.
//!
//! `SPDX-License-Identifier: MIT OR Apache-2.0`
#![cfg_attr(all(coverage_nightly, test), feature(coverage_attribute))]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#![deny(missing_docs)]
#![deny(unsafe_code)]
#![deny(unreachable_pub)]

mod bit_read;
mod bit_write;
mod bytes_cursor;
mod cow;
mod nal_emulation_prevention;
pub mod range_check;
pub mod zero_copy;

pub use bit_read::BitReader;
pub use bit_write::BitWriter;
pub use bytes_cursor::{BytesCursor, BytesCursorExt};
pub use cow::bytes::BytesCow;
pub use cow::string::StringCow;
#[cfg(feature = "serde")]
pub use cow::string::serde::StringCowDeserializer;
pub use nal_emulation_prevention::EmulationPreventionIo;

/// Changelogs generated by [scuffle_changelog]
#[cfg(feature = "docs")]
#[scuffle_changelog::changelog]
pub mod changelog {}
