name: Grind
inputs:
  env:
    description: "The environment variables to set"
    required: false
runs:
  using: "composite"
  steps:
    - name: Fail if not Linux
      shell: bash
      if: ${{ runner.os != 'Linux' }}
      run: |
        echo "::error::This action only supports Linux runners for now."
        exit 1

    - name: Disable hakari
      shell: bash
      run: cargo hakari disable

    - name: Install Valgrind
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      env:
        VALGRIND_VERSION: master
        INSTALL_PATH: /usr/local
      run: |
        set -eo pipefail
        curl -L "https://github.com/scufflecloud/valgrind-builds/releases/download/latest/valgrind-${VALGRIND_VERSION}-$(uname -s)-$(uname -m).tar.gz" | sudo tar -xzf - --strip-components=1 -C $INSTALL_PATH
        echo "VALGRIND_LIB=$INSTALL_PATH/libexec/valgrind" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libc6-dbg

    - name: Setup env
      if: ${{ inputs.env }}
      shell: bash
      run: |
        set -eo pipefail
        env_json=$(cat <<ENV_END_OF_FILE
        ${{ inputs.env}}
        ENV_END_OF_FILE
        )
        for key in $(echo "$env_json" | jq -r 'keys[]'); do
            expanded_key=$(eval echo "$key")
            value=$(echo "$env_json" | jq -r --arg key "$key" '.[$key]')
            expanded_value=$(eval echo "$value")
            echo "$expanded_key=$expanded_value" >> $GITHUB_ENV
            echo "Setting $expanded_key to $expanded_value"
        done

    - name: Run valgrind
      shell: bash
      env:
        RUSTFLAGS: "--cfg reqwest_unstable --cfg valgrind"
      run: cargo nextest run --all-features --no-fail-fast --profile ci
