name: Semver-checks
inputs:
  pr_number:
    description: "The PR number"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run xtask semver checks (against main branch)
      id: semver_checks
      shell: bash
      env:
        RUSTFLAGS: "--cfg reqwest_unstable"
      run: |
        set -eo pipefail
        cargo xtask semver-checks --disable-hakari | tee /tmp/.semver-checks-body $GITHUB_STEP_SUMMARY

    - name: Add/update PR comment
      # skip commenting the summary on forked PRs
      if: ${{ !github.event.pull_request.head.repo.fork }}
      uses: thollander/actions-comment-pull-request@v3
      with:
        file-path: /tmp/.semver-checks-body
        pr-number: ${{ inputs.pr_number }}
        comment-tag: semver-checks
