#![cfg_attr(coverage_nightly, feature(coverage_attribute))]
#![deny(missing_docs)]
#![deny(unreachable_pub)]
#![deny(clippy::undocumented_unsafe_blocks)]
#![deny(clippy::multiple_unsafe_ops_per_block)]

//! Tinc
//! TODO: crate docs.

#[doc(hidden)]
pub mod reexports {
    pub use {axum, chrono, headers_accept, http, linkme, mediatype, prost, regex, schemars, serde, serde_repr, tonic};
}

#[doc(hidden)]
#[path = "private/mod.rs"]
pub mod __private;

/// TincServices are typically generated by the `tinc-build`
/// crate and this trate lets you convert the service
/// into an axum router.
pub trait TincService {
    /// Convert the service into an axum router.
    fn into_router(self) -> axum::Router;
}

/// Include the proto by specifying the package.
#[macro_export]
macro_rules! include_proto {
    ($package:tt) => {
        include!(concat!(env!("OUT_DIR"), concat!("/", $package, ".rs")));
    };
}

pub use tonic::{Code, Request, Response, Result, Status, async_trait};
