name: Setup FFmpeg
description: Installs FFmpeg on the system
inputs:
  version:
    description: "The version of FFmpeg to install"
    required: false
    default: "7.1"
runs:
  using: "composite"
  steps:
    - name: Install System Dependencies
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        set -xeo pipefail
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends nasm

    - name: Install FFmpeg
      shell: bash
      if: ${{ runner.os == 'Linux' || runner.os == 'Windows' }}
      run: |
        set -xeo pipefail

        ARCH='${{ inputs.arch || runner.arch }}'
        OS='${{ inputs.os || runner.os }}'

        case "$ARCH" in
          x86_64|amd64|X64) FF_ARCH="64" ;;
          aarch64|arm64|ARM64) FF_ARCH="arm64" ;;
          *) echo "Unsupported architecture: $ARCH" && exit 1 ;;
        esac

        case "$OS" in
          linux|Linux|LINUX) FF_OS="linux" && FF_EXT="tar.xz" ;;
          windows|Windows|WINDOWS) FF_OS="win" && FF_EXT="zip" ;;
          *) echo "Unsupported operating system: $OS" && exit 1 ;;
        esac

        case "${{ inputs.version || '7.1' }}" in
          "7.1") FILE="ffmpeg-n7.1-latest-${FF_OS}${FF_ARCH}-gpl-shared-7.1.${FF_EXT}" ;;
          "6.1") FILE="ffmpeg-n6.1-latest-${FF_OS}${FF_ARCH}-gpl-shared-6.1.${FF_EXT}" ;;
          "master") FILE="ffmpeg-master-latest-${FF_OS}${FF_ARCH}-gpl-shared.${FF_EXT}" ;;
          *) echo "Unsupported version: ${{ inputs.version }}" && exit 1 ;;
        esac

        FF_URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/${FILE}"

        echo "Downloading FFmpeg from $FF_URL"
        curl -L "$FF_URL" -o ffmpeg.${FF_EXT}

        case "${{ runner.os }}" in
          Linux)
            tar -xvf ffmpeg.${FF_EXT}
            FFMPEG_ROOT="/usr/local"
            ;;
          Windows)
            unzip ffmpeg.${FF_EXT}
            FFMPEG_ROOT="C:/ffmpeg"
            ;;
          *)
            echo "Unsupported operating system: ${{ runner.os }}" && exit 1
        esac

        # Sometimes sudo isnt available, so we need to use the current user
        if ! sudo -v; then
          echo "Sudo is not available, using current user"
          SUDO=""
        else
          SUDO="sudo"
        fi

        ${SUDO} mkdir -p ${FFMPEG_ROOT}/{include,lib,bin}
        ${SUDO} mv ffmpeg-*/include/* ${FFMPEG_ROOT}/include
        ${SUDO} mv ffmpeg-*/lib/* ${FFMPEG_ROOT}/lib
        ${SUDO} mv ffmpeg-*/bin/* ${FFMPEG_ROOT}/bin

        if [ "${{ runner.os }}" = "Linux" ]; then
          # Update the dynamic linker cache
          ${SUDO} ldconfig
        fi

        echo "FFMPEG_PKG_CONFIG_PATH=${FFMPEG_ROOT}/lib/pkgconfig" >> $GITHUB_ENV
        echo "FFMPEG_LIBS_DIR=${FFMPEG_ROOT}/lib" >> $GITHUB_ENV
        echo "FFMPEG_INCLUDE_DIR=${FFMPEG_ROOT}/include" >> $GITHUB_ENV
        echo "${FFMPEG_ROOT}/bin" >> $GITHUB_PATH
        echo "${FFMPEG_ROOT}/lib" >> $GITHUB_PATH
        echo "${FFMPEG_ROOT}/include" >> $GITHUB_PATH

        echo "FFmpeg installed successfully"

    - name: Cache Homebrew Packages
      uses: actions/cache@v4
      if: ${{ runner.os == 'macOS' }}
      with:
        path: |
          /usr/local/Homebrew
          /usr/local/Cellar
          ~/Library/Caches/Homebrew
        key: homebrew-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/workflows/ffmpeg-cache.yaml') }}
        restore-keys: |
          homebrew-${{ runner.os }}-${{ runner.arch }}-

    - name: Install ffmpeg
      shell: bash
      if: ${{ runner.os == 'macOS' }}
      run: |
        set -xeo pipefail

        case "${{ inputs.version || '7.1' }}" in
          "7.1") FILE="ffmpeg@7" ;;
          "6.1") FILE="ffmpeg@" ;;
          "master") FILE="ffmpeg --HEAD" ;;
          *) echo "Unsupported version: ${{ inputs.version }}" && exit 1 ;;
        esac

        brew install $FILE
